#![doc = r" Remusys-MIR Instruction Variant Definitions"]
#![doc = r" NOTE: This file is auto-generated from the RIG-DSL definitions."]
use super::*;
#[derive(Debug, Clone)]
pub enum MirInst {
    GuideNode(super::MirInstCommon),
    CondBr(super::impls::CondBr),
    CBZs(super::impls::CBZs),
    UncondBr(super::impls::UncondBr),
    BReg(super::impls::BReg),
    BLinkLabel(super::impls::BLinkLabel),
    BLinkReg(super::impls::BLinkReg),
    TBZ64(super::impls::TBZ64),
    TBZ32(super::impls::TBZ32),
    ICmp64R(super::impls::ICmp64R),
    ICmp32R(super::impls::ICmp32R),
    ICmp64I(super::impls::ICmp64I),
    ICmp32I(super::impls::ICmp32I),
    FCmp32(super::impls::FCmp32),
    FCmp64(super::impls::FCmp64),
    ICCmp64R(super::impls::ICCmp64R),
    ICCmp32R(super::impls::ICCmp32R),
    ICCmp64I(super::impls::ICCmp64I),
    ICCmp32I(super::impls::ICCmp32I),
    FCCmp32(super::impls::FCCmp32),
    FCCmp64(super::impls::FCCmp64),
    Bin64R(super::impls::Bin64R),
    Bin32R(super::impls::Bin32R),
    MulL(super::impls::MulL),
    Bin64RC(super::impls::Bin64RC),
    Bin32RC(super::impls::Bin32RC),
    Bin64RL(super::impls::Bin64RL),
    Bin32RL(super::impls::Bin32RL),
    Bin64RS(super::impls::Bin64RS),
    Bin64RU(super::impls::Bin64RU),
    Bin32RS(super::impls::Bin32RS),
    Bin32RU(super::impls::Bin32RU),
    Bin64RShift(super::impls::Bin64RShift),
    Bin32RShift(super::impls::Bin32RShift),
    BinF64R(super::impls::BinF64R),
    BinF32R(super::impls::BinF32R),
    MirCopy64(super::impls::MirCopy64),
    MirCopy32(super::impls::MirCopy32),
    MirFCopy64(super::impls::MirFCopy64),
    MirFCopy32(super::impls::MirFCopy32),
    MirPCopy(super::impls::MirPCopy),
    Una64R(super::impls::Una64R),
    Una32R(super::impls::Una32R),
    ExtR(super::impls::ExtR),
    Mov64I(super::impls::Mov64I),
    Mov32I(super::impls::Mov32I),
    Adr(super::impls::Adr),
    UnaFG64(super::impls::UnaFG64),
    UnaGF64(super::impls::UnaGF64),
    UnaF64G32(super::impls::UnaF64G32),
    UnaFG32(super::impls::UnaFG32),
    UnaF32G64(super::impls::UnaF32G64),
    UnaGF32(super::impls::UnaGF32),
    UnaG64F32(super::impls::UnaG64F32),
    UnaG32F64(super::impls::UnaG32F64),
    UnaF64(super::impls::UnaF64),
    UnaF32(super::impls::UnaF32),
    UnaryF32F64(super::impls::UnaryF32F64),
    UnaryF64F32(super::impls::UnaryF64F32),
    FMov64I(super::impls::FMov64I),
    FMov32I(super::impls::FMov32I),
    TenaryG64(super::impls::TenaryG64),
    TenaryG64G32(super::impls::TenaryG64G32),
    TenaryG32(super::impls::TenaryG32),
    TenaryF64(super::impls::TenaryF64),
    TenaryF32(super::impls::TenaryF32),
    LoadStoreGr64(super::impls::LoadStoreGr64),
    LoadStoreGr32(super::impls::LoadStoreGr32),
    LoadStoreF64(super::impls::LoadStoreF64),
    LoadStoreF32(super::impls::LoadStoreF32),
    LoadStoreGr64Base(super::impls::LoadStoreGr64Base),
    LoadStoreGr32Base(super::impls::LoadStoreGr32Base),
    LoadStoreF64Base(super::impls::LoadStoreF64Base),
    LoadStoreF32Base(super::impls::LoadStoreF32Base),
    LoadStoreGr64Indexed(super::impls::LoadStoreGr64Indexed),
    LoadStoreGr32Indexed(super::impls::LoadStoreGr32Indexed),
    LoadStoreF64Indexed(super::impls::LoadStoreF64Indexed),
    LoadStoreF32Indexed(super::impls::LoadStoreF32Indexed),
    LoadStoreGr64Literal(super::impls::LoadStoreGr64Literal),
    LoadStoreGr32Literal(super::impls::LoadStoreGr32Literal),
    LoadStoreF64Literal(super::impls::LoadStoreF64Literal),
    LoadStoreF32Literal(super::impls::LoadStoreF32Literal),
    LoadConst64(super::impls::LoadConst64),
    LoadConstF64(super::impls::LoadConstF64),
    LoadConst64Symbol(super::impls::LoadConst64Symbol),
    MirCall(super::mirops::MirCall),
    MirReturn(super::mirops::MirReturn),
    MirSwitch(super::mirops::MirSwitch),
}
impl MirInst {
    pub fn get_common(&self) -> &super::MirInstCommon {
        match self {
            MirInst::GuideNode(common) => common,
            MirInst::CondBr(inst) => inst.get_common(),
            MirInst::CBZs(inst) => inst.get_common(),
            MirInst::UncondBr(inst) => inst.get_common(),
            MirInst::BReg(inst) => inst.get_common(),
            MirInst::BLinkLabel(inst) => inst.get_common(),
            MirInst::BLinkReg(inst) => inst.get_common(),
            MirInst::TBZ64(inst) => inst.get_common(),
            MirInst::TBZ32(inst) => inst.get_common(),
            MirInst::ICmp64R(inst) => inst.get_common(),
            MirInst::ICmp32R(inst) => inst.get_common(),
            MirInst::ICmp64I(inst) => inst.get_common(),
            MirInst::ICmp32I(inst) => inst.get_common(),
            MirInst::FCmp32(inst) => inst.get_common(),
            MirInst::FCmp64(inst) => inst.get_common(),
            MirInst::ICCmp64R(inst) => inst.get_common(),
            MirInst::ICCmp32R(inst) => inst.get_common(),
            MirInst::ICCmp64I(inst) => inst.get_common(),
            MirInst::ICCmp32I(inst) => inst.get_common(),
            MirInst::FCCmp32(inst) => inst.get_common(),
            MirInst::FCCmp64(inst) => inst.get_common(),
            MirInst::Bin64R(inst) => inst.get_common(),
            MirInst::Bin32R(inst) => inst.get_common(),
            MirInst::MulL(inst) => inst.get_common(),
            MirInst::Bin64RC(inst) => inst.get_common(),
            MirInst::Bin32RC(inst) => inst.get_common(),
            MirInst::Bin64RL(inst) => inst.get_common(),
            MirInst::Bin32RL(inst) => inst.get_common(),
            MirInst::Bin64RS(inst) => inst.get_common(),
            MirInst::Bin64RU(inst) => inst.get_common(),
            MirInst::Bin32RS(inst) => inst.get_common(),
            MirInst::Bin32RU(inst) => inst.get_common(),
            MirInst::Bin64RShift(inst) => inst.get_common(),
            MirInst::Bin32RShift(inst) => inst.get_common(),
            MirInst::BinF64R(inst) => inst.get_common(),
            MirInst::BinF32R(inst) => inst.get_common(),
            MirInst::MirCopy64(inst) => inst.get_common(),
            MirInst::MirCopy32(inst) => inst.get_common(),
            MirInst::MirFCopy64(inst) => inst.get_common(),
            MirInst::MirFCopy32(inst) => inst.get_common(),
            MirInst::MirPCopy(inst) => inst.get_common(),
            MirInst::Una64R(inst) => inst.get_common(),
            MirInst::Una32R(inst) => inst.get_common(),
            MirInst::ExtR(inst) => inst.get_common(),
            MirInst::Mov64I(inst) => inst.get_common(),
            MirInst::Mov32I(inst) => inst.get_common(),
            MirInst::Adr(inst) => inst.get_common(),
            MirInst::UnaFG64(inst) => inst.get_common(),
            MirInst::UnaGF64(inst) => inst.get_common(),
            MirInst::UnaF64G32(inst) => inst.get_common(),
            MirInst::UnaFG32(inst) => inst.get_common(),
            MirInst::UnaF32G64(inst) => inst.get_common(),
            MirInst::UnaGF32(inst) => inst.get_common(),
            MirInst::UnaG64F32(inst) => inst.get_common(),
            MirInst::UnaG32F64(inst) => inst.get_common(),
            MirInst::UnaF64(inst) => inst.get_common(),
            MirInst::UnaF32(inst) => inst.get_common(),
            MirInst::UnaryF32F64(inst) => inst.get_common(),
            MirInst::UnaryF64F32(inst) => inst.get_common(),
            MirInst::FMov64I(inst) => inst.get_common(),
            MirInst::FMov32I(inst) => inst.get_common(),
            MirInst::TenaryG64(inst) => inst.get_common(),
            MirInst::TenaryG64G32(inst) => inst.get_common(),
            MirInst::TenaryG32(inst) => inst.get_common(),
            MirInst::TenaryF64(inst) => inst.get_common(),
            MirInst::TenaryF32(inst) => inst.get_common(),
            MirInst::LoadStoreGr64(inst) => inst.get_common(),
            MirInst::LoadStoreGr32(inst) => inst.get_common(),
            MirInst::LoadStoreF64(inst) => inst.get_common(),
            MirInst::LoadStoreF32(inst) => inst.get_common(),
            MirInst::LoadStoreGr64Base(inst) => inst.get_common(),
            MirInst::LoadStoreGr32Base(inst) => inst.get_common(),
            MirInst::LoadStoreF64Base(inst) => inst.get_common(),
            MirInst::LoadStoreF32Base(inst) => inst.get_common(),
            MirInst::LoadStoreGr64Indexed(inst) => inst.get_common(),
            MirInst::LoadStoreGr32Indexed(inst) => inst.get_common(),
            MirInst::LoadStoreF64Indexed(inst) => inst.get_common(),
            MirInst::LoadStoreF32Indexed(inst) => inst.get_common(),
            MirInst::LoadStoreGr64Literal(inst) => inst.get_common(),
            MirInst::LoadStoreGr32Literal(inst) => inst.get_common(),
            MirInst::LoadStoreF64Literal(inst) => inst.get_common(),
            MirInst::LoadStoreF32Literal(inst) => inst.get_common(),
            MirInst::LoadConst64(inst) => inst.get_common(),
            MirInst::LoadConstF64(inst) => inst.get_common(),
            MirInst::LoadConst64Symbol(inst) => inst.get_common(),
            MirInst::MirCall(inst) => inst.get_common(),
            MirInst::MirReturn(inst) => inst.get_common(),
            MirInst::MirSwitch(inst) => inst.get_common(),
        }
    }
    #[doc = "Returns the opcode of the instruction. This is useful for matching or dispatching logic."]
    pub fn get_opcode(&self) -> MirOP {
        self.get_common().opcode
    }
    pub fn in_operands(&self) -> &[Cell<MirOperand>] {
        match self {
            MirInst::GuideNode(_) => &[],
            MirInst::CondBr(inst) => inst.in_operands(),
            MirInst::CBZs(inst) => inst.in_operands(),
            MirInst::UncondBr(inst) => inst.in_operands(),
            MirInst::BReg(inst) => inst.in_operands(),
            MirInst::BLinkLabel(inst) => inst.in_operands(),
            MirInst::BLinkReg(inst) => inst.in_operands(),
            MirInst::TBZ64(inst) => inst.in_operands(),
            MirInst::TBZ32(inst) => inst.in_operands(),
            MirInst::ICmp64R(inst) => inst.in_operands(),
            MirInst::ICmp32R(inst) => inst.in_operands(),
            MirInst::ICmp64I(inst) => inst.in_operands(),
            MirInst::ICmp32I(inst) => inst.in_operands(),
            MirInst::FCmp32(inst) => inst.in_operands(),
            MirInst::FCmp64(inst) => inst.in_operands(),
            MirInst::ICCmp64R(inst) => inst.in_operands(),
            MirInst::ICCmp32R(inst) => inst.in_operands(),
            MirInst::ICCmp64I(inst) => inst.in_operands(),
            MirInst::ICCmp32I(inst) => inst.in_operands(),
            MirInst::FCCmp32(inst) => inst.in_operands(),
            MirInst::FCCmp64(inst) => inst.in_operands(),
            MirInst::Bin64R(inst) => inst.in_operands(),
            MirInst::Bin32R(inst) => inst.in_operands(),
            MirInst::MulL(inst) => inst.in_operands(),
            MirInst::Bin64RC(inst) => inst.in_operands(),
            MirInst::Bin32RC(inst) => inst.in_operands(),
            MirInst::Bin64RL(inst) => inst.in_operands(),
            MirInst::Bin32RL(inst) => inst.in_operands(),
            MirInst::Bin64RS(inst) => inst.in_operands(),
            MirInst::Bin64RU(inst) => inst.in_operands(),
            MirInst::Bin32RS(inst) => inst.in_operands(),
            MirInst::Bin32RU(inst) => inst.in_operands(),
            MirInst::Bin64RShift(inst) => inst.in_operands(),
            MirInst::Bin32RShift(inst) => inst.in_operands(),
            MirInst::BinF64R(inst) => inst.in_operands(),
            MirInst::BinF32R(inst) => inst.in_operands(),
            MirInst::MirCopy64(inst) => inst.in_operands(),
            MirInst::MirCopy32(inst) => inst.in_operands(),
            MirInst::MirFCopy64(inst) => inst.in_operands(),
            MirInst::MirFCopy32(inst) => inst.in_operands(),
            MirInst::MirPCopy(inst) => inst.in_operands(),
            MirInst::Una64R(inst) => inst.in_operands(),
            MirInst::Una32R(inst) => inst.in_operands(),
            MirInst::ExtR(inst) => inst.in_operands(),
            MirInst::Mov64I(inst) => inst.in_operands(),
            MirInst::Mov32I(inst) => inst.in_operands(),
            MirInst::Adr(inst) => inst.in_operands(),
            MirInst::UnaFG64(inst) => inst.in_operands(),
            MirInst::UnaGF64(inst) => inst.in_operands(),
            MirInst::UnaF64G32(inst) => inst.in_operands(),
            MirInst::UnaFG32(inst) => inst.in_operands(),
            MirInst::UnaF32G64(inst) => inst.in_operands(),
            MirInst::UnaGF32(inst) => inst.in_operands(),
            MirInst::UnaG64F32(inst) => inst.in_operands(),
            MirInst::UnaG32F64(inst) => inst.in_operands(),
            MirInst::UnaF64(inst) => inst.in_operands(),
            MirInst::UnaF32(inst) => inst.in_operands(),
            MirInst::UnaryF32F64(inst) => inst.in_operands(),
            MirInst::UnaryF64F32(inst) => inst.in_operands(),
            MirInst::FMov64I(inst) => inst.in_operands(),
            MirInst::FMov32I(inst) => inst.in_operands(),
            MirInst::TenaryG64(inst) => inst.in_operands(),
            MirInst::TenaryG64G32(inst) => inst.in_operands(),
            MirInst::TenaryG32(inst) => inst.in_operands(),
            MirInst::TenaryF64(inst) => inst.in_operands(),
            MirInst::TenaryF32(inst) => inst.in_operands(),
            MirInst::LoadStoreGr64(inst) => inst.in_operands(),
            MirInst::LoadStoreGr32(inst) => inst.in_operands(),
            MirInst::LoadStoreF64(inst) => inst.in_operands(),
            MirInst::LoadStoreF32(inst) => inst.in_operands(),
            MirInst::LoadStoreGr64Base(inst) => inst.in_operands(),
            MirInst::LoadStoreGr32Base(inst) => inst.in_operands(),
            MirInst::LoadStoreF64Base(inst) => inst.in_operands(),
            MirInst::LoadStoreF32Base(inst) => inst.in_operands(),
            MirInst::LoadStoreGr64Indexed(inst) => inst.in_operands(),
            MirInst::LoadStoreGr32Indexed(inst) => inst.in_operands(),
            MirInst::LoadStoreF64Indexed(inst) => inst.in_operands(),
            MirInst::LoadStoreF32Indexed(inst) => inst.in_operands(),
            MirInst::LoadStoreGr64Literal(inst) => inst.in_operands(),
            MirInst::LoadStoreGr32Literal(inst) => inst.in_operands(),
            MirInst::LoadStoreF64Literal(inst) => inst.in_operands(),
            MirInst::LoadStoreF32Literal(inst) => inst.in_operands(),
            MirInst::LoadConst64(inst) => inst.in_operands(),
            MirInst::LoadConstF64(inst) => inst.in_operands(),
            MirInst::LoadConst64Symbol(inst) => inst.in_operands(),
            MirInst::MirCall(inst) => inst.in_operands(),
            MirInst::MirReturn(inst) => inst.in_operands(),
            MirInst::MirSwitch(inst) => inst.in_operands(),
        }
    }
    pub fn out_operands(&self) -> &[Cell<MirOperand>] {
        match self {
            MirInst::GuideNode(_) => &[],
            MirInst::CondBr(inst) => inst.out_operands(),
            MirInst::CBZs(inst) => inst.out_operands(),
            MirInst::UncondBr(inst) => inst.out_operands(),
            MirInst::BReg(inst) => inst.out_operands(),
            MirInst::BLinkLabel(inst) => inst.out_operands(),
            MirInst::BLinkReg(inst) => inst.out_operands(),
            MirInst::TBZ64(inst) => inst.out_operands(),
            MirInst::TBZ32(inst) => inst.out_operands(),
            MirInst::ICmp64R(inst) => inst.out_operands(),
            MirInst::ICmp32R(inst) => inst.out_operands(),
            MirInst::ICmp64I(inst) => inst.out_operands(),
            MirInst::ICmp32I(inst) => inst.out_operands(),
            MirInst::FCmp32(inst) => inst.out_operands(),
            MirInst::FCmp64(inst) => inst.out_operands(),
            MirInst::ICCmp64R(inst) => inst.out_operands(),
            MirInst::ICCmp32R(inst) => inst.out_operands(),
            MirInst::ICCmp64I(inst) => inst.out_operands(),
            MirInst::ICCmp32I(inst) => inst.out_operands(),
            MirInst::FCCmp32(inst) => inst.out_operands(),
            MirInst::FCCmp64(inst) => inst.out_operands(),
            MirInst::Bin64R(inst) => inst.out_operands(),
            MirInst::Bin32R(inst) => inst.out_operands(),
            MirInst::MulL(inst) => inst.out_operands(),
            MirInst::Bin64RC(inst) => inst.out_operands(),
            MirInst::Bin32RC(inst) => inst.out_operands(),
            MirInst::Bin64RL(inst) => inst.out_operands(),
            MirInst::Bin32RL(inst) => inst.out_operands(),
            MirInst::Bin64RS(inst) => inst.out_operands(),
            MirInst::Bin64RU(inst) => inst.out_operands(),
            MirInst::Bin32RS(inst) => inst.out_operands(),
            MirInst::Bin32RU(inst) => inst.out_operands(),
            MirInst::Bin64RShift(inst) => inst.out_operands(),
            MirInst::Bin32RShift(inst) => inst.out_operands(),
            MirInst::BinF64R(inst) => inst.out_operands(),
            MirInst::BinF32R(inst) => inst.out_operands(),
            MirInst::MirCopy64(inst) => inst.out_operands(),
            MirInst::MirCopy32(inst) => inst.out_operands(),
            MirInst::MirFCopy64(inst) => inst.out_operands(),
            MirInst::MirFCopy32(inst) => inst.out_operands(),
            MirInst::MirPCopy(inst) => inst.out_operands(),
            MirInst::Una64R(inst) => inst.out_operands(),
            MirInst::Una32R(inst) => inst.out_operands(),
            MirInst::ExtR(inst) => inst.out_operands(),
            MirInst::Mov64I(inst) => inst.out_operands(),
            MirInst::Mov32I(inst) => inst.out_operands(),
            MirInst::Adr(inst) => inst.out_operands(),
            MirInst::UnaFG64(inst) => inst.out_operands(),
            MirInst::UnaGF64(inst) => inst.out_operands(),
            MirInst::UnaF64G32(inst) => inst.out_operands(),
            MirInst::UnaFG32(inst) => inst.out_operands(),
            MirInst::UnaF32G64(inst) => inst.out_operands(),
            MirInst::UnaGF32(inst) => inst.out_operands(),
            MirInst::UnaG64F32(inst) => inst.out_operands(),
            MirInst::UnaG32F64(inst) => inst.out_operands(),
            MirInst::UnaF64(inst) => inst.out_operands(),
            MirInst::UnaF32(inst) => inst.out_operands(),
            MirInst::UnaryF32F64(inst) => inst.out_operands(),
            MirInst::UnaryF64F32(inst) => inst.out_operands(),
            MirInst::FMov64I(inst) => inst.out_operands(),
            MirInst::FMov32I(inst) => inst.out_operands(),
            MirInst::TenaryG64(inst) => inst.out_operands(),
            MirInst::TenaryG64G32(inst) => inst.out_operands(),
            MirInst::TenaryG32(inst) => inst.out_operands(),
            MirInst::TenaryF64(inst) => inst.out_operands(),
            MirInst::TenaryF32(inst) => inst.out_operands(),
            MirInst::LoadStoreGr64(inst) => inst.out_operands(),
            MirInst::LoadStoreGr32(inst) => inst.out_operands(),
            MirInst::LoadStoreF64(inst) => inst.out_operands(),
            MirInst::LoadStoreF32(inst) => inst.out_operands(),
            MirInst::LoadStoreGr64Base(inst) => inst.out_operands(),
            MirInst::LoadStoreGr32Base(inst) => inst.out_operands(),
            MirInst::LoadStoreF64Base(inst) => inst.out_operands(),
            MirInst::LoadStoreF32Base(inst) => inst.out_operands(),
            MirInst::LoadStoreGr64Indexed(inst) => inst.out_operands(),
            MirInst::LoadStoreGr32Indexed(inst) => inst.out_operands(),
            MirInst::LoadStoreF64Indexed(inst) => inst.out_operands(),
            MirInst::LoadStoreF32Indexed(inst) => inst.out_operands(),
            MirInst::LoadStoreGr64Literal(inst) => inst.out_operands(),
            MirInst::LoadStoreGr32Literal(inst) => inst.out_operands(),
            MirInst::LoadStoreF64Literal(inst) => inst.out_operands(),
            MirInst::LoadStoreF32Literal(inst) => inst.out_operands(),
            MirInst::LoadConst64(inst) => inst.out_operands(),
            MirInst::LoadConstF64(inst) => inst.out_operands(),
            MirInst::LoadConst64Symbol(inst) => inst.out_operands(),
            MirInst::MirCall(inst) => inst.out_operands(),
            MirInst::MirReturn(inst) => inst.out_operands(),
            MirInst::MirSwitch(inst) => inst.out_operands(),
        }
    }
}
impl crate::base::slablist::SlabRefListNode for MirInst {
    fn new_guide() -> Self {
        MirInst::GuideNode(super::MirInstCommon::new_guide())
    }
    fn load_node_head(&self) -> crate::base::slablist::SlabRefListNodeHead {
        self.get_common().node_head.get()
    }
    fn store_node_head(&self, head: crate::base::slablist::SlabRefListNodeHead) {
        self.get_common().node_head.set(head);
    }
}
